return {
  {
    'folke/tokyonight.nvim',
  },
  {
    'ellisonleao/gruvbox.nvim',
  },
  { 'catppuccin/nvim', name = 'catppuccin', priority = 1000 },
  { 'rebelot/kanagawa.nvim' },
  { 'navarasu/onedark.nvim' },
  { 'sainnhe/everforest' },
  { 'sainnhe/sonokai' },
  { 'morhetz/gruvbox' },
  { 'dracula/vim', name = 'dracula' },
  { 'arcticicestudio/nord-vim' },
  { 'joshdick/onedark.vim' },
  { 'rakr/vim-one' },
  { 'tomasiser/vim-code-dark' },
  { 'ayu-theme/ayu-vim' },
  { 'sainnhe/gruvbox-material' },
  { 'NLKNguyen/papercolor-theme' },
  { 'ghifarit53/tokyonight-vim' },
  { 'cocopon/iceberg.vim' },
  { 'EdenEast/nightfox.nvim' },
  { 'projekt0n/github-nvim-theme' },
  { 'savq/melange-nvim' },
  { 'bluz71/vim-moonfly-colors' },
}
